// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA7QJTaKcQfCv9hXK9niPVN_-IytBwA48',
    appId: '1:542267863783:web:da99b8533972acc60fa842',
    messagingSenderId: '542267863783',
    projectId: 'trackingapp-e4363',
    authDomain: 'trackingapp-e4363.firebaseapp.com',
    storageBucket: 'trackingapp-e4363.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9GpFgqXI4pxcH3lyalqDCaFWboDyPH8',
    appId: '1:542267863783:android:8f46ad0b731671ae0fa842',
    messagingSenderId: '542267863783',
    projectId: 'trackingapp-e4363',
    storageBucket: 'trackingapp-e4363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDX7zmYlySId2jkdl4L6Eeptd_mDSsRs',
    appId: '1:542267863783:ios:5ab66182bb69720e0fa842',
    messagingSenderId: '542267863783',
    projectId: 'trackingapp-e4363',
    storageBucket: 'trackingapp-e4363.firebasestorage.app',
    iosBundleId: 'com.example.trackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDX7zmYlySId2jkdl4L6Eeptd_mDSsRs',
    appId: '1:542267863783:ios:5ab66182bb69720e0fa842',
    messagingSenderId: '542267863783',
    projectId: 'trackingapp-e4363',
    storageBucket: 'trackingapp-e4363.firebasestorage.app',
    iosBundleId: 'com.example.trackingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA7QJTaKcQfCv9hXK9niPVN_-IytBwA48',
    appId: '1:542267863783:web:6411524e683ac1500fa842',
    messagingSenderId: '542267863783',
    projectId: 'trackingapp-e4363',
    authDomain: 'trackingapp-e4363.firebaseapp.com',
    storageBucket: 'trackingapp-e4363.firebasestorage.app',
  );
}
